# HTTP Server.
server:
  address: ":8000"
  dumpRouterMap: true
  routeOverWrite: true
  accessLogEnabled: true
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# Global logging.
logger:
  level: "all"
  stdout: true

# Database.
database:
  logger:
    path: "logs/sql"
    level: "all"
    stdout: true
    ctxKeys: ["RequestId"]

  default:
    link: "mysql:root:admin123@tcp(127.0.0.1:3306)/shop?loc=Local&parseTime=true"
    debug: true

redis:
  default:
    address: 127.0.0.1:6379
    db: 0

  cache:
    address: 127.0.0.1:6379
    db: 1
    idleTimeout: 600