// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Position is the golang structure of table position for DAO operations like Where/Data.
type Position struct {
	g.Meta    `orm:"table:position, do:true"`
	Id        interface{} //
	PicUrl    interface{} // 图片链接
	GoodsName interface{} // 商品名称
	Link      interface{} // 跳转链接
	Status    interface{} // 状态
	Sort      interface{} // 排序
	GoodsId   interface{} // 商品id
	CreatedAt interface{} // 创建时间
	UpdatedAt interface{} // 更新时间
	DeletedAt interface{} // 删除时间
}
