// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Rotation is the golang structure of table rotation for DAO operations like Where/Data.
type Rotation struct {
	g.Meta    `orm:"table:rotation, do:true"`
	Id        interface{} //
	PicUrl    interface{} // 图片链接
	Link      interface{} // 跳转链接
	Sort      interface{} // 排序
	Remark    interface{} // 备注
	Status    interface{} // 状态
	CreatedAt *gtime.Time // 创建时间
	UpdatedAt *gtime.Time // 更新时间
	DeletedAt *gtime.Time // 删除时间
}
