// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"shop/internal/model"
)

type (
	IAdmin interface {
		List(ctx context.Context, in *model.AdminListInput) (out *model.AdminItemListOutput, err error)
		IsExist(ctx context.Context, username string) bool
		Create(ctx context.Context, in *model.AdminCreateInput) (out model.AdminCreateOutput, err error)
		Delete(ctx context.Context, id int) (err error)
		Update(ctx context.Context, in *model.AdminUpdateInput) (err error)
		GetUserByUsernamePassword(ctx context.Context, in model.LoginInput) (out map[string]interface{})
	}
)

var (
	localAdmin IAdmin
)

func Admin() IAdmin {
	if localAdmin == nil {
		panic("implement not found for interface IAdmin, forgot register?")
	}
	return localAdmin
}

func RegisterAdmin(i IAdmin) {
	localAdmin = i
}
