// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"shop/internal/model"
)

type (
	ICategory interface {
		List(ctx context.Context, in *model.CategoryListInput) (out *model.CategoryListItemOutput, err error)
		Create(ctx context.Context, in *model.CategoryCreateInput) (out model.CategoryCreateOutput, err error)
		Delete(ctx context.Context, id int) (err error)
		Update(ctx context.Context, in *model.CategoryUpdateInput) (err error)
	}
)

var (
	localCategory ICategory
)

func Category() ICategory {
	if localCategory == nil {
		panic("implement not found for interface ICategory, forgot register?")
	}
	return localCategory
}

func RegisterCategory(i ICategory) {
	localCategory = i
}
