// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"shop/internal/model"
)

type (
	ICollection interface {
		Create(ctx context.Context, in *model.CollectionCreateInput) (out *model.CollectionCreateOutput, err error)
		Cancel(ctx context.Context, in *model.CollectionCancelInput) (err error)
		List(ctx context.Context, in *model.CollectionListInput) (out *model.CollectionListOutput, err error)
	}
)

var (
	localCollection ICollection
)

func Collection() ICollection {
	if localCollection == nil {
		panic("implement not found for interface ICollection, forgot register?")
	}
	return localCollection
}

func RegisterCollection(i ICollection) {
	localCollection = i
}
