// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"shop/internal/model"

	"github.com/goflyfox/gtoken/gtoken"
	"github.com/gogf/gf/v2/net/ghttp"
)

type (
	ILogin interface {
		Login(ctx context.Context, in *model.LoginInput) (err error)
		LoginBeforeFunc(r *ghttp.Request) (string, interface{})
		LoginAfterFunc(r *ghttp.Request, resp gtoken.Resp)
		AuthAfterFunc(r *ghttp.Request, resp gtoken.Resp)
	}
)

var (
	localLogin ILogin
)

func Login() ILogin {
	if localLogin == nil {
		panic("implement not found for interface ILogin, forgot register?")
	}
	return localLogin
}

func RegisterLogin(i ILogin) {
	localLogin = i
}
