// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// CommentInfo is the golang structure for table comment_info.
type CommentInfo struct {
	Id        int         `json:"id"         description:""`
	ParentId  int         `json:"parent_id"  description:"父级评论id"`
	UserId    int         `json:"user_id"    description:""`
	ObjectId  int         `json:"object_id"  description:""`
	Type      int         `json:"type"       description:"评论类型：1商品 2文章"`
	Content   string      `json:"content"    description:"评论内容"`
	CreatedAt *gtime.Time `json:"created_at" description:""`
	UpdatedAt *gtime.Time `json:"updated_at" description:""`
	DeletedAt *gtime.Time `json:"deleted_at" description:""`
}
