// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Position is the golang structure for table position.
type Position struct {
	Id        int    `json:"id"        description:""`
	PicUrl    string `json:"picUrl"    description:"图片链接"`
	GoodsName string `json:"goodsName" description:"商品名称"`
	Link      string `json:"link"      description:"跳转链接"`
	Status    int    `json:"status"    description:"状态"`
	Sort      int    `json:"sort"      description:"排序"`
	GoodsId   int    `json:"goodsId"   description:"商品id"`
	CreatedAt string `json:"createdAt" description:"创建时间"`
	UpdatedAt string `json:"updatedAt" description:"更新时间"`
	DeletedAt string `json:"deletedAt" description:"删除时间"`
}
