// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// User is the golang structure for table user.
type User struct {
	Id        int    `json:"id"        description:""`
	Username  string `json:"username"  description:"用户名"`
	Password  string `json:"password"  description:"密码"`
	RoleIds   string `json:"roleIds"   description:"角色ids"`
	Sort      int    `json:"sort"      description:"排序"`
	Salt      string `json:"salt"      description:"盐"`
	IsAdmin   int    `json:"isAdmin"   description:"是否是超级管理员"`
	CreatedAt string `json:"createdAt" description:""`
	UpdatedAt string `json:"updatedAt" description:""`
	DeletedAt string `json:"deletedAt" description:""`
}
